import type { VehicleStatusVO } from './types'

/** 车辆列表本地测试数据（字段对齐 CLOUD-STATUS / 1010001，不请求线上 API） */
export const MOCK_VEHICLES: VehicleStatusVO[] = [
  {
    vehicleId: 'LU2606000100',
    clientId: 'LU2606000100',
    vehicleName: '北斗',
    vehicleDescription: '北斗测试',
    emqxUsername: 'LU2606000100',
    online: false,
    updatedAt: Date.now() - 1200,
    createTime: Date.now() - 86400000,
    connectedAt: Date.now() - 120000,
    disconnectedAt: Date.now() - 60000,
    enableConnectToEmqx: true,
    regionName: '深圳灵鱿科技',
    tenantName: 'test',
    positionXyz: { x: 21.23, y: 41.65, yaw: 0 },
    heading: 2.107,
    workStatus: 0,
    battery: 27,
    taskId: '0',
    taskName: '',
    isInNode: true,
    taskProgress: 100,
    speedMps: 0,
    brakeStatus: 0,
    robotStatus: 1,
    vehicleInfo: { odometry: 0, drivingMode: 'auto_drive', vehicleSpeed: 0 },
    faultSummary: { hasFault: false, faultCount: 0, highestFaultLevel: 1 },
    alertMsg: ''
  },
  {
    vehicleId: 'hasun-test',
    clientId: 'hasun-test',
    vehicleName: '测试车-A',
    vehicleDescription: 'tpapi 联调环境测试设备',
    emqxUsername: 'hasun-test',
    online: true,
    updatedAt: Date.now() - 800,
    positionXyz: { x: 21.64, y: 86.28, yaw: 1.42 },
    heading: 81,
    workStatus: 0,
    battery: 85,
    taskId: '',
    taskName: '',
    faultSummary: { hasFault: false, faultCount: 0, highestFaultLevel: 1 }
  },
  {
    vehicleId: 'YW1003',
    clientId: 'robot-003',
    vehicleName: '灵鱿-R3',
    vehicleDescription: '充电区待命，R3 型号',
    emqxUsername: 'robot-003',
    online: true,
    updatedAt: Date.now() - 2000,
    positionXyz: { x: 12.5, y: 45.0, yaw: 0.5 },
    heading: 45,
    workStatus: 3,
    battery: 92,
    taskId: '',
    taskName: '充电',
    faultSummary: { hasFault: false, faultCount: 0, highestFaultLevel: 1 }
  },
  {
    vehicleId: 'YW1004',
    clientId: 'robot-004',
    vehicleName: '灵鱿-Pro',
    vehicleDescription: '通信离线，待检修',
    emqxUsername: 'robot-004',
    online: false,
    updatedAt: Date.now() - 3600000,
    positionXyz: { x: 0, y: 0, yaw: 0 },
    heading: 0,
    workStatus: 0,
    battery: 0,
    taskId: '',
    faultSummary: { hasFault: true, faultCount: 1, highestFaultLevel: 3 },
    alertMsg: '通信故障'
  },
  {
    vehicleId: 'YW1005',
    clientId: 'robot-005',
    vehicleName: '灵鱿-Y5',
    vehicleDescription: '驱动电机异常，限制运行',
    emqxUsername: 'robot-005',
    online: true,
    updatedAt: Date.now() - 500,
    positionXyz: { x: 8.2, y: 15.6, yaw: 2.1 },
    heading: 120,
    workStatus: 2,
    battery: 45,
    taskId: '0',
    faultSummary: { hasFault: true, faultCount: 2, highestFaultLevel: 2 },
    alertMsg: '驱动电机异常'
  },
  {
    vehicleId: 'YW1006',
    clientId: 'robot-006',
    vehicleName: '灵鱿-X1',
    vehicleDescription: '移库任务执行中',
    emqxUsername: 'robot-006',
    online: true,
    updatedAt: Date.now() - 300,
    positionXyz: { x: 33.1, y: 12.8, yaw: -0.3 },
    heading: 270,
    workStatus: 4,
    battery: 78,
    taskId: 'T-emergency',
    taskName: '移库',
    faultSummary: { hasFault: false, faultCount: 0, highestFaultLevel: 1 }
  }
]
